// const Users = require('./users-model');
// const db = require('../data/dbConfig');

// describe('users model', function () {
//   beforeEach(async () => {
//     await db('users').truncate();
//   })

//   describe('find()', function () {
//     it('GET list of all users from the database', async function () {
//       //checks that the database is empty
//       const users = await db('users');
//       expect(users).toHaveLength(0);
//       // call add passing three users
//       await Users.add({
//         username: 'cuphead',
//         password: 'swellbattle',
//         email: 'cuphead@inkewllisle.com',
//         phone_number: '6666666666'
//       });
//       await Users.add({
//         username: 'mugman',
//         password: 'thingsareheatingup',
//         email: 'mugman@inkewllisle.com',
//         phone_number: '9999999999'
//       });
//       await Users.add({
//         username: 'kingdice',
//         password: 'dontyoumesswithhim',
//         email: 'king@inkewllisle.com',
//         phone_number: '7777777777'
//       });
//       // open the database and see that the new users are there
//       const newusers = await db('users');
//       expect(newusers).toHaveLength(3);
//       expect(users).not.toBeNull();

//     })
//   })
//   describe('findById(id)', function () {
//     it('Check if the user has an id autogenerated', async function () {
//       // call add passing two users
//       await Users.add({
//         username: 'cuphead',
//         password: 'swellbattle',
//         email: 'cuphead@inkewllisle.com',
//         phone_number: '6666666666'
//       });
//       // open the database and see that the new users are there
//       const user = await db('users');
//       expect(user[0]).toHaveProperty('id');
//     })
//   })
//   describe('add(user)', function () {
//     it('POST the new user to the database', async function () {
//       //checks that the database is empty
//       const users = await db('users');
//       expect(users).toHaveLength(0);
//       // call add passing two users
//       await Users.add({
//         username: 'hollowknight',
//         password: 'slurp',
//         email: 'hollow@cityoftears.com',
//         phone_number: '7454346876'
//       });
//       // open the database and see that the new user is there
//       const newUser = await db('users');
//       expect(newUser).toHaveLength(1);
//     })
//   })
//   describe('update(id, changes)', function () {
//     it('UPDATE the user from the database', async function () {
//       // check that the table is empty

//       // add a user

//       // check that the user is there

//       // delete the user

//       // check that the user is gone 

//     })
//   })

//   describe('remove(id)', function () {
//     it('DELETE a user from the database', async function () {
//       //checks that the database is empty
//       const users = await db('users');
//       expect(users).toHaveLength(0);
//       //adds a user to the database
//       await Users.add({
//         username: 'shantae',
//         password: 'poottoot',
//         email: 'shantae@tasseltown.com',
//         phone_number: '7575757575'
//       })
//       //open the db and see that the new user is there
//       const newUsers = await db('users');
//       expect(newUsers).toHaveLength(1);
//       //delete the user by id
//       await Users.remove(newUsers[0].id);
//       //check that the user is gone
//       const updatedDB = await db('users');
//       expect(updatedDB).toHaveLength(0);
//     })
//   })
// })